from . import animal_breed
from . import animal_care
from . import animal_health_status
from . import animal_identification
from . import animal_owner
from . import animal_protocol
from . import animal_species
from . import animal_status
from . import animal_actes
