[project]
name = "odoo-addons-akretion-sacpa-modules"
version = "18.0.20260409.0"
dependencies = [
    "odoo-addon-accord==18.0.*",
    "odoo-addon-animacare==18.0.*",
    "odoo-addon-animal_fieldservice==18.0.*",
    "odoo-addon-animal_helpdesk==18.0.*",
    "odoo-addon-animal_identification==18.0.*",
    "odoo-addon-city_insee==18.0.*",
    "odoo-addon-converter==18.0.*",
    "odoo-addon-invoice_move_webhook==18.0.*",
    "odoo-addon-redner==18.0.*",
    "odoo-addon-service_agreement==18.0.*",
    "odoo-addon-vigipet==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
